"""Add AI chatbot tables

Revision ID: 702d4ce46e13
Revises: 20250824_add_idempotency_key_to_reports
Create Date: 2025-08-25 19:30:34.800944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702d4ce46e13'
down_revision: Union[str, None] = '20250824_add_idempotency_key_to_reports'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - made idempotent ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'chatbot_users' not in existing_tables:
        op.create_table('chatbot_users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=64), nullable=False),
        sa.Column('password', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        try:
            op.create_index(op.f('ix_chatbot_users_email'), 'chatbot_users', ['email'], unique=False)
        except Exception:
            pass

    if 'chatbot_chats' not in existing_tables:
        op.create_table('chatbot_chats',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('visibility', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['chatbot_users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        try:
            op.create_index(op.f('ix_chatbot_chats_user_id'), 'chatbot_chats', ['user_id'], unique=False)
        except Exception:
            pass

    if 'chatbot_documents' not in existing_tables:
        op.create_table('chatbot_documents',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('kind', sa.String(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['chatbot_users.id'], ),
        sa.PrimaryKeyConstraint('id', 'created_at')
        )
        try:
            op.create_index(op.f('ix_chatbot_documents_user_id'), 'chatbot_documents', ['user_id'], unique=False)
        except Exception:
            pass

    if 'chatbot_suggestions' not in existing_tables:
        op.create_table('chatbot_suggestions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('document_id', sa.UUID(), nullable=False),
        sa.Column('document_created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('original_text', sa.Text(), nullable=False),
        sa.Column('suggested_text', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_resolved', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['chatbot_users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        try:
            op.create_index(op.f('ix_chatbot_suggestions_user_id'), 'chatbot_suggestions', ['user_id'], unique=False)
        except Exception:
            pass

    if 'chatbot_messages_v2' not in existing_tables:
        op.create_table('chatbot_messages_v2',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('chat_id', sa.UUID(), nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('parts', sa.JSON(), nullable=False),
        sa.Column('attachments', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['chat_id'], ['chatbot_chats.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        try:
            op.create_index(op.f('ix_chatbot_messages_v2_chat_id'), 'chatbot_messages_v2', ['chat_id'], unique=False)
        except Exception:
            pass

    if 'chatbot_streams' not in existing_tables:
        op.create_table('chatbot_streams',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('chat_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['chat_id'], ['chatbot_chats.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        try:
            op.create_index(op.f('ix_chatbot_streams_chat_id'), 'chatbot_streams', ['chat_id'], unique=False)
        except Exception:
            pass

    if 'chatbot_votes_v2' not in existing_tables:
        op.create_table('chatbot_votes_v2',
        sa.Column('chat_id', sa.UUID(), nullable=False),
        sa.Column('message_id', sa.UUID(), nullable=False),
        sa.Column('is_upvoted', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['chat_id'], ['chatbot_chats.id'], ),
        sa.ForeignKeyConstraint(['message_id'], ['chatbot_messages_v2.id'], ),
        sa.PrimaryKeyConstraint('chat_id', 'message_id')
        )
    # Safe cleanup for legacy objects (guarded for SQLite and idempotency)
    # We avoid hard-failing if these objects don't exist in the target DB.
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # NOTE: historic_analysis_status table is managed by migration 6453e7b2f4b5
    # Don't drop it here - it's still actively used
    # (Originally this migration dropped it by mistake)

    # Drop legacy indexes if they exist
    for index_name in [
        'idx_contact_ident',
        'idx_conversations_chat_end',
        'idx_messages_chat_ts',
        'idx_messages_conversation',
        'idx_messages_guid',
        'idx_reactions_guid',
        'idx_reactions_original_guid',
        'ix_reports_idempotency_key',
    ]:
        try:
            op.execute(f'DROP INDEX IF EXISTS {index_name}')
        except Exception:
            pass

    # Drop column only if present (SQLite-safe via batch_alter_table)
    try:
        report_cols = [c['name'] for c in inspector.get_columns('reports')]
        if 'idempotency_key' in report_cols:
            with op.batch_alter_table('reports') as batch_op:
                batch_op.drop_column('idempotency_key')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('idempotency_key', sa.VARCHAR(), nullable=True))
    op.create_index('ix_reports_idempotency_key', 'reports', ['idempotency_key'], unique=False)
    op.create_index('idx_reactions_original_guid', 'reactions', ['original_message_guid'], unique=False)
    op.create_index('idx_reactions_guid', 'reactions', ['guid'], unique=1)
    op.create_index('idx_messages_guid', 'messages', ['guid'], unique=1)
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_messages_chat_ts', 'messages', ['chat_id', 'timestamp'], unique=False)
    op.create_index('idx_conversations_chat_end', 'conversations', ['chat_id', 'end_time'], unique=False)
    op.create_index('idx_contact_ident', 'contact_identifiers', ['identifier'], unique=False)
    # NOTE: historic_analysis_status creation removed from downgrade
    # (it was backwards - downgrade shouldn't create tables, that's upgrade's job)
    # The table is properly created by migration 6453e7b2f4b5
    op.drop_table('chatbot_votes_v2')
    op.drop_index(op.f('ix_chatbot_streams_chat_id'), table_name='chatbot_streams')
    op.drop_table('chatbot_streams')
    op.drop_index(op.f('ix_chatbot_messages_v2_chat_id'), table_name='chatbot_messages_v2')
    op.drop_table('chatbot_messages_v2')
    op.drop_index(op.f('ix_chatbot_suggestions_user_id'), table_name='chatbot_suggestions')
    op.drop_table('chatbot_suggestions')
    op.drop_index(op.f('ix_chatbot_documents_user_id'), table_name='chatbot_documents')
    op.drop_table('chatbot_documents')
    op.drop_index(op.f('ix_chatbot_chats_user_id'), table_name='chatbot_chats')
    op.drop_table('chatbot_chats')
    op.drop_index(op.f('ix_chatbot_users_email'), table_name='chatbot_users')
    op.drop_table('chatbot_users')
    # ### end Alembic commands ###
