"""initial_schema

Revision ID: 6554b713161e
Revises: 
Create Date: 2025-07-29 17:05:10.459000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6554b713161e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_identifier', sa.String(), nullable=True),
    sa.Column('chat_name', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_message_date', sa.DateTime(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('last_embedding_update', sa.DateTime(), nullable=True),
    sa.Column('wrapped_in_progress', sa.Boolean(), nullable=True),
    sa.Column('wrapped_done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_chat_identifier'), 'chats', ['chat_identifier'], unique=True)
    op.create_index(op.f('ix_chats_created_date'), 'chats', ['created_date'], unique=False)
    op.create_index(op.f('ix_chats_last_message_date'), 'chats', ['last_message_date'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('avatar', sa.LargeBinary(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('is_me', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('retrieval_function_ref', sa.String(), nullable=False),
    sa.Column('parameter_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('failed_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('queue_name', sa.String(length=100), nullable=False),
    sa.Column('args', sa.Text(), nullable=True),
    sa.Column('kwargs', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('live_sync_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('friendly_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('placeholder_mapping', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('response_schema_json', sa.JSON(), nullable=True),
    sa.Column('default_llm_config_json', sa.JSON(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', 'category', name='uq_prompt_template_name_version_category')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_participants',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'contact_id')
    )
    op.create_table('chat_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_subscription_id', sa.String(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_subscriptions_chat_id'), 'chat_subscriptions', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_subscriptions_current_period_end'), 'chat_subscriptions', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_chat_subscriptions_id'), 'chat_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_subscriptions_provider_subscription_id'), 'chat_subscriptions', ['provider_subscription_id'], unique=True)
    op.create_index(op.f('ix_chat_subscriptions_status'), 'chat_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_chat_subscriptions_user_id'), 'chat_subscriptions', ['user_id'], unique=False)
    op.create_table('commitment_analysis_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.String(length=255), nullable=False),
    sa.Column('message_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analysis_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitment_analysis_generations_chat_id'), 'commitment_analysis_generations', ['chat_id'], unique=False)
    op.create_index(op.f('ix_commitment_analysis_generations_generation_id'), 'commitment_analysis_generations', ['generation_id'], unique=True)
    op.create_index(op.f('ix_commitment_analysis_generations_message_timestamp'), 'commitment_analysis_generations', ['message_timestamp'], unique=False)
    op.create_table('commitment_event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('generation_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitment_event_log_chat_id'), 'commitment_event_log', ['chat_id'], unique=False)
    op.create_index(op.f('ix_commitment_event_log_event_id'), 'commitment_event_log', ['event_id'], unique=True)
    op.create_table('contact_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_identifiers_identifier'), 'contact_identifiers', ['identifier'], unique=False)
    op.create_table('context_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_definition_id', sa.Integer(), nullable=False),
    sa.Column('parameter_values', sa.JSON(), nullable=True),
    sa.Column('resolved_content', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['context_definition_id'], ['context_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('initiator_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('gap_threshold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_chat_id'), 'conversations', ['chat_id'], unique=False)
    op.create_index(op.f('ix_conversations_initiator_id'), 'conversations', ['initiator_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('prompt_template_id', sa.Integer(), nullable=False),
    sa.Column('combined_prompt_text', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('cost', sa.String(), nullable=True),
    sa.Column('context_selections', sa.JSON(), nullable=True),
    sa.Column('suggested_preview_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commitment_id', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('to_person_id', sa.Integer(), nullable=False),
    sa.Column('commitment_text', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_specificity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('modifications', sa.JSON(), nullable=True),
    sa.Column('reminder_data', sa.JSON(), nullable=True),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_method', sa.String(), nullable=True),
    sa.Column('final_due_date', sa.Date(), nullable=True),
    sa.Column('analysis_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_generation_id', sa.String(length=255), nullable=True),
    sa.Column('source_conversation_id', sa.Integer(), nullable=True),
    sa.Column('last_modified_conversation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['last_modified_conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['to_person_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitments_commitment_id'), 'commitments', ['commitment_id'], unique=True)
    op.create_table('completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('prompt_template_id', sa.Integer(), nullable=False),
    sa.Column('compiled_prompt_text', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completions_chat_id'), 'completions', ['chat_id'], unique=False)
    op.create_index(op.f('ix_completions_contact_id'), 'completions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_completions_conversation_id'), 'completions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_completions_prompt_template_id'), 'completions', ['prompt_template_id'], unique=False)
    op.create_table('emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('emotion_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotions_chat_id'), 'emotions', ['chat_id'], unique=False)
    op.create_index(op.f('ix_emotions_contact_id'), 'emotions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_emotions_conversation_id'), 'emotions', ['conversation_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_chat_id'), 'entities', ['chat_id'], unique=False)
    op.create_index(op.f('ix_entities_contact_id'), 'entities', ['contact_id'], unique=False)
    op.create_index(op.f('ix_entities_conversation_id'), 'entities', ['conversation_id'], unique=False)
    op.create_table('humor_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_humor_items_chat_id'), 'humor_items', ['chat_id'], unique=False)
    op.create_index(op.f('ix_humor_items_contact_id'), 'humor_items', ['contact_id'], unique=False)
    op.create_index(op.f('ix_humor_items_conversation_id'), 'humor_items', ['conversation_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_from_me', sa.Boolean(), nullable=True),
    sa.Column('message_type', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('guid', sa.String(), nullable=True),
    sa.Column('associated_message_guid', sa.String(), nullable=True),
    sa.Column('reply_to_guid', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_timestamp', 'messages', ['chat_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_guid'), 'messages', ['guid'], unique=True)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_table('report_displays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('generated_code', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('cost', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_chat_id'), 'topics', ['chat_id'], unique=False)
    op.create_index(op.f('ix_topics_contact_id'), 'topics', ['contact_id'], unique=False)
    op.create_index(op.f('ix_topics_conversation_id'), 'topics', ['conversation_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('is_sticker', sa.Boolean(), nullable=True),
    sa.Column('guid', sa.String(), nullable=True),
    sa.Column('uti', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_created_date'), 'attachments', ['created_date'], unique=False)
    op.create_index(op.f('ix_attachments_guid'), 'attachments', ['guid'], unique=True)
    op.create_index(op.f('ix_attachments_message_id'), 'attachments', ['message_id'], unique=False)
    op.create_table('conversation_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('prompt_template_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('temporal_workflow_id', sa.String(), nullable=True),
    sa.Column('completion_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['completion_id'], ['completions.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'prompt_template_id', name='uq_conversation_prompt_template')
    )
    op.create_index(op.f('ix_conversation_analyses_conversation_id'), 'conversation_analyses', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_analyses_id'), 'conversation_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_analyses_prompt_template_id'), 'conversation_analyses', ['prompt_template_id'], unique=False)
    op.create_index(op.f('ix_conversation_analyses_status'), 'conversation_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_conversation_analyses_temporal_workflow_id'), 'conversation_analyses', ['temporal_workflow_id'], unique=False)
    op.create_table('published_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('report_display_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('preview_image_url', sa.String(), nullable=True),
    sa.Column('preview_description', sa.Text(), nullable=True),
    sa.Column('is_password_protected', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('password_hint', sa.String(), nullable=True),
    sa.Column('server_slug', sa.String(), nullable=True),
    sa.Column('server_display_id', sa.Integer(), nullable=True),
    sa.Column('server_published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_display_id'], ['report_displays.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_message_guid', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('reaction_type', sa.Integer(), nullable=True),
    sa.Column('guid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['original_message_guid'], ['messages.guid'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reactions_chat_id'), 'reactions', ['chat_id'], unique=False)
    op.create_index(op.f('ix_reactions_guid'), 'reactions', ['guid'], unique=True)
    op.create_index(op.f('ix_reactions_original_message_guid'), 'reactions', ['original_message_guid'], unique=False)
    op.create_index(op.f('ix_reactions_sender_id'), 'reactions', ['sender_id'], unique=False)
    op.create_index(op.f('ix_reactions_timestamp'), 'reactions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reactions_timestamp'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_sender_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_original_message_guid'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_guid'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_chat_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_table('published_reports')
    op.drop_index(op.f('ix_conversation_analyses_temporal_workflow_id'), table_name='conversation_analyses')
    op.drop_index(op.f('ix_conversation_analyses_status'), table_name='conversation_analyses')
    op.drop_index(op.f('ix_conversation_analyses_prompt_template_id'), table_name='conversation_analyses')
    op.drop_index(op.f('ix_conversation_analyses_id'), table_name='conversation_analyses')
    op.drop_index(op.f('ix_conversation_analyses_conversation_id'), table_name='conversation_analyses')
    op.drop_table('conversation_analyses')
    op.drop_index(op.f('ix_attachments_message_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_guid'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_created_date'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_topics_conversation_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_contact_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_chat_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_table('report_displays')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_guid'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index('idx_chat_timestamp', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_humor_items_conversation_id'), table_name='humor_items')
    op.drop_index(op.f('ix_humor_items_contact_id'), table_name='humor_items')
    op.drop_index(op.f('ix_humor_items_chat_id'), table_name='humor_items')
    op.drop_table('humor_items')
    op.drop_index(op.f('ix_entities_conversation_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_contact_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_chat_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_emotions_conversation_id'), table_name='emotions')
    op.drop_index(op.f('ix_emotions_contact_id'), table_name='emotions')
    op.drop_index(op.f('ix_emotions_chat_id'), table_name='emotions')
    op.drop_table('emotions')
    op.drop_index(op.f('ix_completions_prompt_template_id'), table_name='completions')
    op.drop_index(op.f('ix_completions_conversation_id'), table_name='completions')
    op.drop_index(op.f('ix_completions_contact_id'), table_name='completions')
    op.drop_index(op.f('ix_completions_chat_id'), table_name='completions')
    op.drop_table('completions')
    op.drop_index(op.f('ix_commitments_commitment_id'), table_name='commitments')
    op.drop_table('commitments')
    op.drop_table('reports')
    op.drop_index(op.f('ix_conversations_initiator_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_chat_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('context_selections')
    op.drop_index(op.f('ix_contact_identifiers_identifier'), table_name='contact_identifiers')
    op.drop_table('contact_identifiers')
    op.drop_index(op.f('ix_commitment_event_log_event_id'), table_name='commitment_event_log')
    op.drop_index(op.f('ix_commitment_event_log_chat_id'), table_name='commitment_event_log')
    op.drop_table('commitment_event_log')
    op.drop_index(op.f('ix_commitment_analysis_generations_message_timestamp'), table_name='commitment_analysis_generations')
    op.drop_index(op.f('ix_commitment_analysis_generations_generation_id'), table_name='commitment_analysis_generations')
    op.drop_index(op.f('ix_commitment_analysis_generations_chat_id'), table_name='commitment_analysis_generations')
    op.drop_table('commitment_analysis_generations')
    op.drop_index(op.f('ix_chat_subscriptions_user_id'), table_name='chat_subscriptions')
    op.drop_index(op.f('ix_chat_subscriptions_status'), table_name='chat_subscriptions')
    op.drop_index(op.f('ix_chat_subscriptions_provider_subscription_id'), table_name='chat_subscriptions')
    op.drop_index(op.f('ix_chat_subscriptions_id'), table_name='chat_subscriptions')
    op.drop_index(op.f('ix_chat_subscriptions_current_period_end'), table_name='chat_subscriptions')
    op.drop_index(op.f('ix_chat_subscriptions_chat_id'), table_name='chat_subscriptions')
    op.drop_table('chat_subscriptions')
    op.drop_table('chat_participants')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('prompt_templates')
    op.drop_table('live_sync_state')
    op.drop_table('failed_tasks')
    op.drop_table('context_definitions')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_chats_last_message_date'), table_name='chats')
    op.drop_index(op.f('ix_chats_created_date'), table_name='chats')
    op.drop_index(op.f('ix_chats_chat_identifier'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
